"""
Django settings for advanced_features_and_security project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kf%sx0+b-prnrenji7q8zjq3wg5wrl&o=$-_&@0khv86tjygb*'

# SECURITY WARNING: don't run with debug turned on in production!

# ✅ SECURITY SETTINGS (important for production)

DEBUG = False  # never True in production

# Prevent browsers from XSS attacks
SECURE_BROWSER_XSS_FILTER = True  

# Prevent content type sniffing
SECURE_CONTENT_TYPE_NOSNIFF = True  

# Stop site from being framed (clickjacking protection)
X_FRAME_OPTIONS = "DENY"  

# Ensure cookies only sent over HTTPS
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'LibraryProject',
    # 'bookshelf',
    'accounts',
    'csp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',  # Content Security Policy middleware
]
# ---------------------------------------
# CSP CONFIGURATION
# ---------------------------------------

# ✅ Restrict what sources can load content
CSP_DEFAULT_SRC = ("'self'",)   # only load from same origin
CSP_STYLE_SRC = ("'self'", "https://fonts.googleapis.com")  # allow Google Fonts
CSP_SCRIPT_SRC = ("'self'",)    # only scripts from same origin


ROOT_URLCONF = 'advanced_features_and_security.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'advanced_features_and_security.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'accounts_db',
        'USER': 'postgres',
        'PASSWORD': 'Bmk@justaqua',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Tell Django to use our custom user model instead of the default
AUTH_USER_MODEL = "accounts.CustomUser"


# ✅ Tell Django to trust the proxy header for HTTPS
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# ✅ Force HTTPS
SECURE_SSL_REDIRECT = True  # redirect all HTTP to HTTPS

# ✅ HTTP Strict Transport Security (HSTS)
SECURE_HSTS_SECONDS = 31536000  # one year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# ✅ Secure cookies (already set earlier, but repeat for clarity)
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# ✅ Extra security headers
X_FRAME_OPTIONS = "DENY"                 # prevent clickjacking
SECURE_CONTENT_TYPE_NOSNIFF = True       # stop MIME sniffing
SECURE_BROWSER_XSS_FILTER = True         # enable browser XSS filter
